export const PURCHASE_CONT = 'PURCHASE_CONT';
export const PURCHASE_CANCEL = 'PURCHASE_CANCEL'
export const CHECKOUT_CONT = 'CHECKOUT_CONT'
export const CHECKOUT_CANCEL = 'CHECKOUT_CANCEL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'